### ISSUE TITLE
LCmodel  execution error

### ISSUE THREAD

**Issue by smcch** [Computational-Imaging-LAB/MRS_Education#4]
Hi ! Can you please help me to solve this error.

- Linux installation

- OS:  Ubuntu 20 WSL

I got this error:

~$ lcmgui
 
    *** LCModel elapsed time = 0 seconds ***.
 
    *** LCModel finished ***
cp: cannot specify '*table': No such file or directory

**Comment by abdullahbas** [comment]
Have you seen the pop-up after installation? I mean after running `bash manual-install` LCModel GUI should pop-up

**Comment by smcch** [comment]
Yes, I have. I can load and set the parameters. The error I mentioned happens after clicking 'Run LCmodel'. 
Please find attached the screenshots of all the steps I took.

![lcmodel_5](https://github.com/Computational-Imaging-LAB/MRS_Education/assets/87584415/bb1b474c-0b82-4b2f-962c-63ebd534fe06)
![lcmodel_4](https://github.com/Computational-Imaging-LAB/MRS_Education/assets/87584415/03db4195-3c32-4913-b7f0-535688da8310)
![lcmodel_3](https://github.com/Computational-Imaging-LAB/MRS_Education/assets/87584415/caa2d725-8277-49fc-a02c-b5cecbe0904f)
![lcmodel_2](https://github.com/Computational-Imaging-LAB/MRS_Education/assets/87584415/0066613d-176e-4ae8-9e12-462aa57f9490)
![lcmodel_1](https://github.com/Computational-Imaging-LAB/MRS_Education/assets/87584415/fcda80fc-0277-4c42-9893-129491ec5c25)

**Comment by abdullahbas** [comment]
After a discussion with @GHaleHatay, we think that it is about the input data.  The error code "MYDATA 2" in the first SS is mentioned in http://s-provencher.com/pub/LCModel/manual/manual.pdf. We think it will be better to check the manual of LCModel. Also you can ask MRSHub about the error you are encountering. 

If the problem is not about the input data I think you have some kind of permission error on WSL to write to the exact folder. Therefore it says there is not *.table file. It is an output file of LCModel and I think it needs it to continue on further processes. Firstly, please try to `ls -l` on the save path from Ubuntu terminal to see if there is any lack of appropriate permissions for your user. If there is a lack, can you try to change the folder permission settings by typing `sudo chmod 777 <folder> ` .

**Comment by smcch** [comment]
Thanks @abdullahbas, the problem was my input data. Files exported from my Philips workstation were corrupted. I tried with DICOM format and now works fine.
